bookstore/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$',views.homepage),
    url(r'^add$',views.new_book),
    url(r'^list_all', views.list_books),
    url(r'^mod/(\d+)$', views.mod_book_info),
    url(r'^del/(\d+)$', views.del_book),
]

mywebsite_bookstore/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import url
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^bookstore/',include('bookstore.urls')),
]

bookstore/models.py
from django.db import models


# Create your models here.
class Book(models.Model):
    title = models.CharField("书名", max_length=50, default="untitled")
    pub_house = models.CharField("出版社", max_length=100, default='')
    price = models.DecimalField('定价',
                                max_digits=7,
                                decimal_places=2,
                                default=0.0)
    market_price = models.DecimalField('零售价',
                                       max_digits=7,
                                       decimal_places=2,
                                       default=9999)

bookstore/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models


# Create your views here.
def homepage(request):
    return render(request, 'index.html')


#添加新书VSCode + Django：objects报错
def new_book(request):
    if request.method == 'GET':
        return render(request, 'new_book.html')
    elif request.method == 'POST':
        title = request.POST.get('title', '')
        pub_house = request.POST.get('pub_house', '')
        price = request.POST.get('price', '')
        market_price = request.POST.get('market_price', '')
        # 用Book.object管理器的create方法来创建新书
        abook = models.Book.objects.create(title=title,
                                           price=price,
                                           market_price=market_price,
                                           pub_house=pub_house)
        print('添加新书,成功添加新书:', abook.title)
        return HttpResponse('<a href="/bookstore">添加新书成功，点我跳转到首页</a>')


# 查看新书
def list_books(request):
    books = models.Book.objects.all()
    return render(request, 'book_list.html', locals())


# 修改图书
def mod_book_info(request, book_id):
    # 先根据book_id 找到对应的一本书
    try:
        abook = models.Book.objects.get(id=book_id)
    except:
        return HttpResponse("没有找到ID为" + book_id + "的图书信息")

    if request.method == 'GET':
        return render(request, "mod_price.html", locals())
    elif request.method == 'POST':
        try:
            m_price = request.POST.get('market_price', '0.0')
            abook.market_price = m_price
            abook.save()  # 提交修改
            return HttpResponse("修改成功")
        except:
            return HttpResponse("修改失败")

# 删除图书
from django.http import HttpResponseRedirect  # 改入 HttpResponseRedirect模块用于 重定向url
def del_book(request, book_id):
    try:
        abook = models.Book.objects.get(id=book_id)
        abook.delete()
        return HttpResponseRedirect('/bookstore/list_all')
    except:
        return HttpResponse("没有找到ID为" + book_id + "的图书信息,删除失败")

templates/book_list.html
<!doctype html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>图书列表</title>
        </head>
        <body>
            <a href="/bookstore">返回首页</a>
            <table>
                <tr>
                    <th>书名</th>
                    <th>出版社</th>
                    <th>定价</th>
                    <th>零售价</th>
                    <th>修改</th>
                    <th>删除</th>
                </tr>
            {% for abook in books %}
                <tr>
                    <td>{{ abook.title }}</td>
                    <td>{{ abook.pub_house }}</td>
                    <td>{{ abook.price }}</td>
                    <td>{{ abook.market_price }}</td>
                    <td><a href="/bookstore/mod/{{ abook.id }}">修改</a></td>
                    <td><a href="/bookstore/del/{{ abook.id }}">删除</a></td>
                </tr>
            {% endfor %}
            </table>
        </body>
        </html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>书库首页</title>
</head>
<body>
    <ul>
        <li><a href="/bookstore/add">添加新图书</a></li>
        <li><a href="/bookstore/list_all">显示所有图书</a>
        </li>
        </ul>
</body>
</html>

templates/mod_price.html
<!doctype html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>修改价格</title>
        </head>
        <body>
            <form action="/bookstore/mod/{{ abook.id }}" method="post">
                <div>书名: {{ abook.title }}</div>
                <div>版社名: {{ abook.pub_house }}</div>
                <div>定价: {{ abook.price }}</div>
                <div>
                    <input type="text" name="market_price" value="{{ abook.market_price }}"placeholder="零售价" required>
                </div>
                <div>
                    <input type="submit" value="修改价格">
                </div>
            </form>
        </body>
        </html>

templates/new_book.html
<!doctype html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>添加新书</title>
        </head>
        <body>
            <form action="/bookstore/add" method="post">
                <div>
                    <label for="id_new">书名</label>
                    <input type="text" name="title" placeholder="请输入新书名" required id="id_new">
                </div>
                <div>
                    <label for="id_pub">出版社</label>
                    <input type="text" name="pub_house" placeholder="请输入出版社名" required id="id_pub">
                </div>
                <div>
                    <label for="id_price">定价</label>
                    <input type="text" name="price" placeholder="请输入定价" required id="id_price">
                </div>
                <div>
                    <label for="id_mk_price">零售价</label>
                    <input type="text" name="market_price" placeholder="请输入零售价" required id="id_mk_price">
                </div>
                <div>
                    <input type="submit" value="添加新书">
                </div>
            </form>
        </body>
        </html>